"""remove materials column from spells table

Revision ID: 034a7c543793
Revises: 8ead2bbc70a7
Create Date: 2023-07-25 12:23:00.104077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034a7c543793'
down_revision = '8ead2bbc70a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.drop_column('material')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
