"""create tables: users, characters. campaigns, spells

Revision ID: da4fa6f50adb
Revises: 
Create Date: 2023-07-25 09:52:35.625661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4fa6f50adb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('join_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('character_class', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('hit_point_max', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('strength_score', sa.Integer(), nullable=True),
    sa.Column('dexterity_score', sa.Integer(), nullable=True),
    sa.Column('constitution_score', sa.Integer(), nullable=True),
    sa.Column('intelligence_score', sa.Integer(), nullable=True),
    sa.Column('wisdom_score', sa.Integer(), nullable=True),
    sa.Column('charisma_score', sa.Integer(), nullable=True),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('senses', sa.String(), nullable=True),
    sa.Column('armor_proficiencies', sa.String(), nullable=True),
    sa.Column('weapon_proficiencies', sa.String(), nullable=True),
    sa.Column('tool_proficiencies', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('higher_level', sa.String(), nullable=True),
    sa.Column('spell_range', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('components', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('is_ritual', sa.Integer(), nullable=True),
    sa.Column('requires_concentration', sa.Integer(), nullable=True),
    sa.Column('casting_time', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('spells')
    op.drop_table('characters')
    op.drop_table('campaign')
    # ### end Alembic commands ###
